"use client";
import {useEffect,useState} from 'react';
import Forecast from '@/components/forecast';
import {Activity,ArrowUpRight,ArrowRight,Bookmark,ChevronRight,CircleHelp,Globe2,Layers3,Newspaper,RefreshCw,Search,ShieldCheck,Sparkles,TrendingUp,Wallet} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
type Story={title:string;source:string;url:string;date:string;category:string;summary:string;signal:number;assets:string[]};
type Rate={date:string;quote:string;rate:number};
type Feed={news:Story[];rates:Rate[];history:Rate[];errors:string[];fetchedAt:string};
const demos:Story[]=[
{title:'Снижение ставок: окно возможностей для облигаций',source:'Сценарий · денежная политика',url:'https://www.federalreserve.gov/monetarypolicy.htm',date:'',category:'Экономика',summary:'Замедление инфляции может открыть путь к снижению ставок и поддержать цены облигаций. Длинные выпуски чувствительнее к изменению доходности.',signal:1,assets:['TLT','BND']},
{title:'Инвестиции в ИИ поддерживают спрос на полупроводники',source:'Сценарий · технологии',url:'https://investor.nvidia.com/',date:'',category:'Технологии',summary:'Расходы на центры обработки данных могут поддержать выручку поставщиков. Высокая оценка компаний увеличивает риск коррекции.',signal:1,assets:['NVDA','MSFT']},
{title:'Сильный доллар: что это значит для ваших накоплений',source:'Сценарий · валюты',url:'https://www.ecb.europa.eu/',date:'',category:'Валюты',summary:'Разница процентных ставок влияет на валюты. Эффект укрепления доллара для ваших накоплений зависит от валюты будущих расходов.',signal:0,assets:['USD','EUR']},
{title:'Дивиденды: устойчивость выплат важнее высокой доходности',source:'Сценарий · дивиденды',url:'https://www.investor.gov/',date:'',category:'Дивиденды',summary:'Сопоставляйте выплаты со свободным денежным потоком и долгом. Будущие дивиденды не гарантированы.',signal:0,assets:['SCHD','JNJ']}];
const assets=[
{ticker:'BND',name:'Vanguard Total Bond Market',type:'Облигации',color:'blue',idea:'Стабильность дохода',risk:'Умеренный',why:'Широкая корзина американских облигаций. Цена может снижаться при росте рыночных ставок. Для инвестора с расходами в другой валюте существует валютный риск.',factor:'Процентные ставки'},
{ticker:'MSFT',name:'Microsoft Corporation',type:'Акции',color:'sky',idea:'Долгосрочный рост',risk:'Повышенный',why:'Облако и ИИ — потенциальные драйверы выручки. Риски: высокая оценка, расходы на инфраструктуру и конкуренция.',factor:'Облако и искусственный интеллект'},
{ticker:'SCHD',name:'Schwab US Dividend Equity',type:'Дивиденды',color:'purple',idea:'Дивидендный доход',risk:'Повышенный',why:'Фонд дивидендных акций США. Выплаты и стоимость паёв могут падать. Дивидендная стратегия не заменяет денежный резерв.',factor:'Прибыль и устойчивость выплат'},
{ticker:'NVDA',name:'NVIDIA Corporation',type:'Акции',color:'lime',idea:'Технологический рост',risk:'Высокий',why:'Зависит от спроса на ускорители ИИ, экспортных ограничений и инвестиционного цикла. Перед покупкой необходимы актуальная цена и отчётность.',factor:'Спрос на вычисления'},
{ticker:'TLT',name:'iShares 20+ Year Treasury',type:'Облигации',color:'slate',idea:'Снижение ставок',risk:'Высокий',why:'Длинные казначейские облигации чувствительны к ставкам. Даже при низком кредитном риске возможны значительные просадки цены.',factor:'Долгосрочные доходности'}];
function Spark({seed=0}:{seed?:number}){return <svg className="spark" viewBox="0 0 108 45" aria-hidden="true"><polyline points={Array.from({length:22},(_,i)=>`${i*5},${33-i*.8+Math.sin(i*1.7+seed)*6}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="1.8"/></svg>}
export default function Home(){
const [view,setView]=useState('Обзор рынка'),[category,setCategory]=useState('Все новости'),[query,setQuery]=useState(''),[demo,setDemo]=useState(true),[feed,setFeed]=useState<Feed|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[period,setPeriod]=useState('1М'),[selected,setSelected]=useState<(typeof assets)[number]|null>(null),[method,setMethod]=useState(false),[saved,setSaved]=useState<string[]>([]),[risk,setRisk]=useState('Все риски');
useEffect(()=>{try{const s=JSON.parse(localStorage.getItem('meridian-watchlist')||'[]');if(Array.isArray(s))setSaved(s.filter(x=>typeof x==='string'))}catch{}},[]);
const toggle=(ticker:string)=>setSaved(p=>{const n=p.includes(ticker)?p.filter(x=>x!==ticker):[...p,ticker];try{localStorage.setItem('meridian-watchlist',JSON.stringify(n))}catch{}return n});
async function refresh(){setLoading(true);setError('');try{const r=await fetch('/api/market');if(!r.ok)throw Error('Источники недоступны. Попробуйте снова.');setFeed(await r.json());setDemo(false)}catch(e){setError(e instanceof Error?e.message:'Ошибка загрузки')}finally{setLoading(false)}}
useEffect(()=>{const d=document as Document&{modelContext?:{registerTool:(t:unknown,o:unknown)=>void}};if(!d.modelContext)return;const c=new AbortController();try{d.modelContext.registerTool({name:'navigate_market',description:'Открыть раздел аналитики',inputSchema:{type:'object',properties:{section:{type:'string',enum:['Обзор рынка','Новости','Акции','Облигации','Дивиденды','Валюты','Избранное']}},required:['section'],additionalProperties:false},execute:async(input:{section:string})=>{if(!['Обзор рынка','Новости','Акции','Облигации','Дивиденды','Валюты','Избранное'].includes(input.section))throw Error('Неизвестный раздел');setView(input.section);return{section:input.section}},annotations:{readOnlyHint:false}},{signal:c.signal})}catch{}return()=>c.abort()},[]);
const stories=(demo?demos:feed?.news||[]).filter(n=>(category==='Все новости'||n.category===category)&&`${n.title} ${n.assets.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
const filtered=assets.filter(a=>(!['Акции','Облигации','Дивиденды','Избранное'].includes(view)||(view==='Избранное'?saved.includes(a.ticker):a.type===view))&&(risk==='Все риски'||a.risk===risk)&&`${a.name} ${a.ticker}`.toLowerCase().includes(query.toLowerCase()));
const history=(feed?.history||[]).filter(r=>r.quote==='USD').sort((a,b)=>a.date.localeCompare(b.date)).slice(period==='1Н'?-5:period==='1М'?-22:period==='3М'?-66:-366);
const values=demo?Array.from({length:period==='1Н'?7:45},(_,i)=>100+i*.15+Math.sin(i*.65)*1.1+Math.cos(i*1.7)*.5):history.map(r=>r.rate);
const min=Math.min(...values),max=Math.max(...values),path=values.map((v,i)=>`${i?'L':'M'}${i/(values.length-1||1)*760},${160-(v-min)/(max-min||1)*120}`).join(' '),last=history.at(-1),change=history.length>1?(last!.rate/history[0].rate-1)*100:null;
return <div className="app-shell"><aside className="sidebar"><a className="brand" href="/"><span className="brandmark"><Activity size={23}/></span>meridian<span className="brand-dot">.</span></a><div className="workspace"><Globe2 size={20}/><div>Личный терминал<small>Ваш взгляд на рынок</small></div></div><span className="nav-label">АНАЛИТИКА</span><nav>{[{name:'Обзор рынка',icon:Layers3},{name:'Новости',icon:Newspaper},{name:'Акции',icon:TrendingUp},{name:'Облигации',icon:ShieldCheck},{name:'Дивиденды',icon:Wallet},{name:'Валюты',icon:Globe2}].map(({name,icon:Icon})=><button key={name} className={view===name?'nav-item active':'nav-item'} onClick={()=>setView(name)}><Icon size={19}/>{name}{name==='Новости'&&<span className="count">{demo?4:feed?.news.length||0}</span>}</button>)}</nav><span className="nav-label second-label">МОЁ ПРОСТРАНСТВО</span><button className={view==='Избранное'?'nav-item active':'nav-item'} onClick={()=>setView('Избранное')}><Bookmark size={19}/>Избранное<span className="count">{saved.length}</span></button><div className="sidebar-bottom"><div className="quiet-card"><span className="little-symbol">✳</span><strong>Сначала — понимание.<br/>Затем — решение.</strong><p>Смотрите на причины движения рынка, а не только на цифры.</p><button onClick={()=>setMethod(true)}>Как работает анализ <ArrowUpRight size={15}/></button></div><button className="help" onClick={()=>setMethod(true)}><CircleHelp size={17}/> Методология и источники</button><div className="profile"><span>И</span><div>Инвестор<small>Личное пространство</small></div><i/></div></div></aside>
<main><header className="topbar"><div className="breadcrumb">Аналитика <ChevronRight size={14}/><b>{view}</b></div><div className="top-actions"><label className="search"><Search size={17}/><input aria-label="Поиск" placeholder="Поиск новостей и активов" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌕</kbd></label><button className="icon-button" aria-label="Методология" onClick={()=>setMethod(true)}><CircleHelp size={19}/></button><span className="avatar">И</span></div></header>
<div className="content"><div className="page-heading"><div><div className="eyebrow"><span/> ГЛОБАЛЬНЫЕ РЫНКИ · ЛИЧНЫЙ ОБЗОР</div><h1>{view}</h1><p>Большая картина для взвешенных решений.</p></div><button className="refresh" onClick={refresh} disabled={loading}><RefreshCw size={16} className={loading?'spinning':''}/>{loading?'Обновляем…':'Обновить данные'}</button></div>
<div className="data-strip"><div><span className={demo?'status-dot amber':'status-dot'}/><b>{demo?'Демонстрационный режим':'Внешние источники'}</b><span>{demo?'Примеры сценариев · не текущие котировки':`Загрузка: ${new Date(feed?.fetchedAt||Date.now()).toLocaleString('ru-RU')}`}</span></div><button onClick={()=>demo?refresh():setDemo(true)} disabled={loading}>{demo?'Загрузить свежие данные':'Показать пример'}<ArrowRight size={14}/></button></div>
{(error||(!demo&&!!feed?.errors.length))&&<div className="notice" role="status">{error||feed?.errors.join(' · ')}</div>}
<section className="market-cards">{(demo?[{name:'S&P 500',sub:'Акции США',value:'5 842,47',delta:'+0,82%'},{name:'NASDAQ',sub:'Технологии',value:'18 421,09',delta:'+1,24%'},{name:'US 10Y',sub:'Доходность облигаций',value:'4,28%',delta:'−0,04 п.п.'},{name:'EUR / USD',sub:'Валютный рынок',value:'1,0842',delta:'+0,18%'}]:['USD','GBP','CHF','JPY'].map(quote=>{const r=feed?.rates.find(x=>x.quote===quote);return{name:`EUR / ${quote}`,sub:r?`Курс на ${r.date}`:'Нет данных',value:r?r.rate.toLocaleString('ru-RU',{maximumFractionDigits:4}):'—',delta:'Дневной курс'}})).map((c,i)=><article className="market-card" key={c.name}><div className="market-card-title"><b>{c.name}</b><span>{demo?'ПРИМЕР':'FX'}</span></div><small>{c.sub}</small><div className="market-card-bottom"><div><strong>{c.value}</strong><span className={i===2&&demo?'negative':'positive'}>{c.delta}</span></div>{demo&&<Spark seed={i}/>}</div></article>)}</section>
<div className="main-grid"><div className="main-column">
{['Обзор рынка','Валюты'].includes(view)&&<section className="panel chart-panel"><div className="section-head"><div><h2>Пульс валютного рынка <span className="tag">EUR / USD</span></h2><p>{demo?'Пример динамики · индексированная шкала':'Сколько долларов стоит один евро'}</p></div><div className="periods">{['1Н','1М','3М','1Г'].map(p=><button key={p} className={period===p?'chosen':''} onClick={()=>setPeriod(p)}>{p}</button>)}</div></div><div className="chart-number">{demo?values.at(-1)!.toFixed(1):last?last.rate.toLocaleString('ru-RU',{maximumFractionDigits:4}):'—'}<span className={change!==null&&change<0?'negative':'positive'}>{demo?`↗ +${((values.at(-1)!/values[0]-1)*100).toFixed(1)}%`:change!==null?`${change>0?'↗ +':'↘ '}${change.toFixed(2)}%`:'Нет истории'}<small> за период</small></span></div><div className="chart">{values.length>1?<><div className="gridlines"><span>{max.toFixed(demo?0:3)}</span><span>{((max+min)/2).toFixed(demo?0:3)}</span><span>{min.toFixed(demo?0:3)}</span></div><svg viewBox="0 0 760 190" preserveAspectRatio="none" role="img" aria-label={demo?'Демонстрационный график':'Исторический курс EUR USD'}><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#1da584" stopOpacity=".17"/><stop offset="100%" stopColor="#1da584" stopOpacity="0"/></linearGradient></defs><path d={`${path} L760,190 L0,190 Z`} fill="url(#chart-fill)"/><path d={path} fill="none" stroke="#188769" strokeWidth="2.5" vectorEffect="non-scaling-stroke"/></svg></>:<div className="empty">История недоступна. Обновите данные.</div>}</div><div className="chart-axis"><span>{demo?'Начало периода':history[0]?.date}</span><span>{demo?'Демонстрационная динамика':'Frankfurter · дневные курсы'}</span><span>{demo?'Конец периода':last?.date}</span></div><div className="chart-note"><Activity size={15}/>{demo?'Динамика — иллюстрация, не прогноз доходности.':'Исторический тренд не гарантирует продолжение движения.'}</div></section>}
{view==='Валюты'&&<Forecast history={feed?.history||[]} demo={demo}/>} 
{['Обзор рынка','Новости'].includes(view)&&<section className="news-section"><div className="section-head"><h2>Что движет рынком <span className="subtle-count">{stories.length}</span></h2><span className="muted">{demo?'Сценарии для изучения':'Заголовки первоисточников'}</span></div><Tabs value={category} onValueChange={setCategory}><TabsList className="news-tabs" variant="line">{['Все новости','Экономика','Технологии','Валюты','Дивиденды'].map(c=><TabsTrigger value={c} key={c}>{c}</TabsTrigger>)}</TabsList></Tabs><div className="news-list">{stories.map((n,i)=><article className="news-item" key={n.url+n.title}><div className={`news-art art-${i%4}`} aria-hidden="true">{i%4===0?<Globe2/>:i%4===1?<Layers3/>:i%4===2?<Activity/>:<Wallet/>}<span>{n.category}</span></div><div className="news-copy"><div className="news-meta">{n.source}<span>·</span>{n.date?new Date(n.date).toLocaleDateString('ru-RU'):'Учебный сценарий'}</div><a href={n.url} target="_blank" rel="noreferrer"><h3>{n.title}<ArrowUpRight size={16}/></h3></a><p>{n.summary}</p><div className="news-tags"><span className={n.signal>0?'signal positive':n.signal<0?'signal negative':'signal neutral'}><Activity size={13}/> {n.signal>0?'Позитивная лексика':n.signal<0?'Негативная лексика':'Нейтральный контекст'}</span>{n.assets.map(a=><span className="asset-tag" key={a}>{a}</span>)}</div></div></article>)}{!stories.length&&<div className="empty">Нет новостей для выбранного фильтра. Измените поиск или обновите источники.</div>}</div></section>}
{!['Новости','Валюты'].includes(view)&&<section className="panel asset-panel"><div className="section-head"><div><h2>{view==='Избранное'?'Избранные активы':'Активы в фокусе'}</h2><p>Кандидаты для изучения · без сигнала к покупке</p></div><select aria-label="Уровень риска" value={risk} onChange={e=>setRisk(e.target.value)}>{['Все риски','Умеренный','Повышенный','Высокий'].map(r=><option key={r}>{r}</option>)}</select></div><Table><TableHeader><TableRow><TableHead>Актив</TableHead><TableHead>Инвестиционная идея</TableHead><TableHead>Риск</TableHead><TableHead><span className="sr-only">Избранное</span></TableHead></TableRow></TableHeader><TableBody>{filtered.map(a=><TableRow key={a.ticker}><TableCell><button className="asset-name" onClick={()=>setSelected(a)}><span className={`ticker-icon ${a.color}`}>{a.ticker.slice(0,2)}</span><span><b>{a.ticker}</b><small>{a.name}</small></span></button></TableCell><TableCell><span className="idea">{a.idea}</span></TableCell><TableCell><span className={`risk ${a.risk==='Высокий'?'high':''}`}><i/>{a.risk}</span></TableCell><TableCell><button className="bookmark" aria-label={`${saved.includes(a.ticker)?'Удалить':'Добавить'} ${a.ticker} в избранное`} onClick={()=>toggle(a.ticker)}><Bookmark size={17} fill={saved.includes(a.ticker)?'currentColor':'none'}/></button></TableCell></TableRow>)}</TableBody></Table>{!filtered.length&&<div className="empty">Активов пока нет. Добавьте их в избранное или измените фильтр.</div>}</section>}
</div><aside className="right-column"><section className="insight-card"><div className="insight-label"><Sparkles size={17}/> АНАЛИТИЧЕСКИЙ ФОКУС</div><h2>Сохранить капитал.<br/>Увидеть возможности.</h2><p>{demo?'В сценарии снижения ставок внимание смещается к качественным облигациям и компаниям с устойчивым денежным потоком.':'Сопоставляйте новости с валютой ваших расходов, горизонтом вложений и допустимой просадкой.'}</p><div className="insight-line"/><div className="focus-row"><ShieldCheck size={20}/><div><b>Защита капитала</b><small>Качество долга и диверсификация</small></div></div><div className="focus-row"><TrendingUp size={20}/><div><b>Потенциал роста</b><small>Прибыль, технологии, оценка</small></div></div><button onClick={()=>setMethod(true)}>Основания и ограничения <ArrowRight size={15}/></button><small className="insight-footer">Объяснимые правила · не персональный совет</small></section>
<section className="panel currencies"><div className="section-head"><h2>Валютный радар</h2><Globe2 size={17}/></div><p>Сила валюты относительно EUR</p>{['USD','GBP','CHF','JPY'].map((c,i)=>{const rows=feed?.history.filter(r=>r.quote===c).sort((a,b)=>a.date.localeCompare(b.date))||[];const delta=rows.length>1?(rows[0].rate/rows.at(-1)!.rate-1)*100:null;return <div className="currency-row" key={c}><span className="currency-flag">{['$','£','₣','¥'][i]}</span><div><b>{c}</b><small>{['Доллар США','Фунт стерлингов','Швейцарский франк','Японская иена'][i]}</small></div><span className={demo?(i===1?'negative':'positive'):delta===null?'muted':delta>=0?'positive':'negative'}>{demo?(i===1?'↘ Снижение':'↗ Рост'):delta===null?'Нет данных':`${delta>0?'+':''}${delta.toFixed(1)}%`}</span></div>})}<div className="radar-note">{demo?'Пример сигналов. Не прогноз.':'Изменение за год. Не вероятность роста.'}</div></section><section className="mini-note"><ShieldCheck size={21}/><div><b>Ваш риск — в ваших руках</b><p>Новость не равна торговому сигналу. Учитывайте комиссии, налоги и валюту будущих расходов.</p></div></section></aside></div>
<footer><span><span className="brand-mini">✳</span> meridian <span className="footer-separator">/</span> Больше контекста. Осознаннее решения.</span><button onClick={()=>setMethod(true)}>Данные и методология <ArrowUpRight size={13}/></button></footer></div></main>
<Dialog open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><DialogContent className="detail-dialog"><DialogTitle>{selected?.ticker} · {selected?.name}</DialogTitle><DialogDescription>Кандидат для исследования, не рекомендация к покупке</DialogDescription><p>{selected?.why}</p><div className="detail-facts"><span>Риск <b>{selected?.risk}</b></span><span>Ключевой фактор <b>{selected?.factor}</b></span></div><p className="muted">Котировки, объявленные даты и суммы дивидендов не подключены. До покупки проверьте отчётность и условия у брокера.</p><button className="refresh" onClick={()=>selected&&toggle(selected.ticker)}><Bookmark size={16}/>{selected&&saved.includes(selected.ticker)?'Удалить из избранного':'Добавить в избранное'}</button></DialogContent></Dialog>
<Dialog open={method} onOpenChange={setMethod}><DialogContent className="detail-dialog"><DialogTitle>Как устроен анализ</DialogTitle><DialogDescription>Источники, логика и ограничения</DialogDescription><p>Обновление загружает заголовки RSS ФРС, ЕЦБ и технологических изданий, а также дневные валютные курсы Frankfurter. Даты и ошибки источников показаны отдельно.</p><p>Лексический анализ ищет слова роста и снижения в заголовках. Он не понимает все причинно-следственные связи и не оценивает вероятность прибыли. Валютный тренд — историческое изменение, а не прогноз.</p><p>Карточки активов — справочные идеи. Текущие цены акций, доходности облигаций и календарь объявленных дивидендов требуют поставщика данных. Демонстрационные значения вымышлены.</p><p>Инвестиции могут принести убыток. Для персонального выбора нужны бюджет, горизонт, валюта расходов и допустимая просадка.</p><div className="source-links"><a href="https://frankfurter.dev/" target="_blank" rel="noreferrer">Frankfurter ↗</a><a href="https://www.federalreserve.gov/feeds/feeds.htm" target="_blank" rel="noreferrer">ФРС ↗</a><a href="https://www.ecb.europa.eu/rss/html/index.en.html" target="_blank" rel="noreferrer">ЕЦБ ↗</a></div></DialogContent></Dialog></div>
}

