"use client";
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ChevronLeft,ChevronRight,Pause,Play,Radio,Sparkles} from 'lucide-react';
import {dailyIdeas,relevantNews} from '@/lib/ideas';
import {allAssets} from '@/lib/market-catalog';
import type {Story} from '@/lib/news';
import StoryBrief from '@/components/story-brief';
import AssetIcon from '@/components/asset-icon';
export function IdeasBanner({news,onSelect}:{news:Story[];onSelect:(ticker:string)=>void}){
 const ideas=dailyIdeas(news);const [ticker,setTicker]=useState(''),[paused,setPaused]=useState(false),[hovered,setHovered]=useState(false),[focused,setFocused]=useState(false),[hidden,setHidden]=useState(false),[reduced,setReduced]=useState(false);
 const touchStart=useRef<{x:number;y:number}|null>(null);const index=Math.max(0,ideas.findIndex(i=>i.ticker===ticker));const active=ideas[index];const running=ideas.length>1&&!paused&&!hovered&&!focused&&!hidden&&!reduced;
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const motion=()=>setReduced(media.matches),visibility=()=>setHidden(document.hidden);motion();visibility();media.addEventListener('change',motion);document.addEventListener('visibilitychange',visibility);return()=>{media.removeEventListener('change',motion);document.removeEventListener('visibilitychange',visibility)}},[]);
 const order=ideas.map(i=>i.ticker).join(',');
 useEffect(()=>{if(!running)return;const sequence=order.split(',');const timer=setTimeout(()=>setTicker(sequence[(index+1)%sequence.length]),8000);return()=>clearTimeout(timer)},[running,order,index]);
 function step(direction:number){if(ideas.length>1)setTicker(ideas[(index+direction+ideas.length)%ideas.length].ticker)}
 return <section className="ideas-banner" aria-label="Идеи дня" aria-roledescription="карусель" onMouseEnter={()=>setHovered(true)} onMouseLeave={()=>setHovered(false)} onFocusCapture={()=>setFocused(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setFocused(false)}}>
 <div className="idea-ambient" aria-hidden="true"><span/><span/><span/></div>
 <div className="idea-top"><div className="idea-label"><Radio size={14}/><span>НОВОСТНОЙ РАДАР</span><span className="idea-date">{new Date().toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}</span></div><span className="idea-curated"><Sparkles size={13}/> В фокусе сегодня</span></div>
 {active?<><div className="idea-stage" onTouchStart={e=>{touchStart.current={x:e.touches[0].clientX,y:e.touches[0].clientY}}} onTouchEnd={e=>{if(touchStart.current!==null){const delta=e.changedTouches[0].clientX-touchStart.current.x,vertical=e.changedTouches[0].clientY-touchStart.current.y;if(Math.abs(delta)>55&&Math.abs(delta)>Math.abs(vertical))step(delta<0?1:-1)}touchStart.current=null}} onTouchCancel={()=>{touchStart.current=null}}>
 {ideas.map((idea,i)=>{const asset=allAssets.find(a=>a.ticker===idea.ticker);return <article className={'idea-slide'+(i===index?' is-active':'')} key={idea.ticker} aria-hidden={i!==index} inert={i!==index} aria-roledescription="слайд" aria-label={idea.ticker+' · '+(i+1)+' из '+ideas.length}>
 <div className="idea-copy"><div className="idea-verdict"><span/>{idea.verdict}</div><div className="idea-identity"><AssetIcon ticker={idea.ticker} name={asset?.name} className="idea-asset-icon"/><div><h2>{asset?.name||idea.ticker}</h2><div className="idea-symbol">{idea.ticker}<span>·</span>{asset?.exchange||'Мировой рынок'}</div></div></div><p className="idea-reason">{idea.reason}</p><div className="idea-evidence"><span>{String(idea.supporting.length).padStart(2,'0')}</span> {idea.supporting.length%10===1&&idea.supporting.length%100!==11?'публикация':idea.supporting.length%10>=2&&idea.supporting.length%10<=4&&(idea.supporting.length%100<12||idea.supporting.length%100>14)?'публикации':'публикаций'} за последние 72 часа</div><button className="btn primary idea-cta" onClick={()=>onSelect(idea.ticker)}>График и аргументы <ArrowUpRight size={18}/></button></div>
 <div className="idea-art" aria-hidden="true"><div className="idea-orbit orbit-outer"/><div className="idea-orbit orbit-inner"/><div className="idea-art-logo"><AssetIcon ticker={idea.ticker} name={asset?.name}/></div><span className="idea-art-code">{idea.ticker}</span><span className="idea-art-caption">СОБЫТИЯ. КОНТЕКСТ. ВАШ ВЫБОР.</span></div>
 </article>})}</div><div className="idea-bottom"><span className="idea-disclaimer">Новостной сигнал, не гарантия доходности.<br/>Цена входа не оценена.</span><div className="idea-navigation"><div className="idea-dots" aria-label="Выбор идеи">{ideas.map((item,i)=><button key={item.ticker} aria-label={'Идея '+item.ticker} aria-pressed={i===index} onClick={()=>setTicker(item.ticker)}><span/></button>)}</div><span className="idea-count">{String(index+1).padStart(2,'0')}<span> / {String(ideas.length).padStart(2,'0')}</span></span>{ideas.length>1&&<><button className="idea-control" aria-label="Предыдущая идея" onClick={()=>step(-1)}><ChevronLeft size={17}/></button><button className="idea-control" aria-label="Следующая идея" onClick={()=>step(1)}><ChevronRight size={17}/></button><button className="idea-control idea-pause" aria-label={paused?'Включить автоперелистывание':'Приостановить автоперелистывание'} aria-pressed={paused} onClick={()=>setPaused(p=>!p)}>{paused?<Play size={14}/>:<Pause size={14}/>}</button></>}</div></div></>:<div className="idea-empty"><Sparkles size={28}/><h2>Ждём подтверждённых поводов</h2><p>В свежих новостях пока недостаточно оснований для идеи покупки. Подборка появится автоматически.</p></div>}
 </section>
}
export function AssetEvidence({ticker,news}:{ticker:string;news:Story[]}){
 const related=relevantNews(news,ticker),idea=dailyIdeas(news).find(i=>i.ticker===ticker);
 return <section className="asset-evidence"><div className="kicker">КОНТЕКСТ ПОКУПКИ · {ticker}</div><h2>{idea?'Почему стоит рассмотреть актив':'Что известно об активе'}</h2><p>{idea?.reason||'Свежего положительного сигнала недостаточно для рекомендации покупки.'}</p>{idea&&<p className="method-note">{idea.risks.join(' ')}</p>}{related.length?related.slice(0,8).map(n=><article className="evidence-story" key={n.url}><div className="news-meta"><b>{n.source}</b><time>{new Date(n.date).toLocaleDateString('ru-RU')}</time><span>{n.signal>0?'Позитивный фактор':n.signal<0?'Риск':'Контекст'}</span></div><h3>{n.ru?.title||n.title}</h3><StoryBrief story={n}/>{(n.catalyst||n.concern)&&<p>{n.concern||n.catalyst}</p>}</article>):<p>В подключённых источниках пока нет публикаций, прямо связанных с {ticker}.</p>}</section>
}
