"use client";
import {useEffect,useMemo,useState} from 'react';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {ArrowLeftRight,ArrowUpRight,ChartNoAxesCombined,Globe2,Search,Clock3} from 'lucide-react';
import {majorCurrencies,currencyName} from '@/lib/market-catalog';
import {fx,validateRates,withinPeriod,pct,displayRate,type Rate} from '@/lib/market-data';
import TradingChart from './trading-chart';
import CurrencyIcon from './currency-icon';
import {forecast} from '@/lib/forecast';
export default function CurrencyTerminal({theme,expanded=false,initialQuote='USD'}:{theme:'light'|'dark';expanded?:boolean;initialQuote?:string}){
 const [base,setBase]=useState('EUR'),[quote,setQuote]=useState(initialQuote),[rates,setRates]=useState<Rate[]>([]),[history,setHistory]=useState<Rate[]>([]),[period,setPeriod]=useState(30),[mode,setMode]=useState('history'),[search,setSearch]=useState(''),[listMode,setListMode]=useState('major'),[error,setError]=useState(''),[busy,setBusy]=useState(true),[checked,setChecked]=useState('');
 useEffect(()=>{const ctrl=new AbortController();let loading=false;const load=async()=>{if(loading||ctrl.signal.aborted)return;loading=true;setBusy(true);try{const date=new Date();date.setUTCFullYear(date.getUTCFullYear()-1);const [latest,past]=await Promise.all([fx(`rates?base=${base}`,ctrl.signal),fx(`rates?base=${base}&quotes=${quote}&from=${date.toISOString().slice(0,10)}`,ctrl.signal)]);if(ctrl.signal.aborted)return;setRates(validateRates(latest));setHistory(validateRates(past).filter(r=>r.quote===quote).sort((a,b)=>a.date.localeCompare(b.date)));setChecked(new Date().toLocaleTimeString('ru-RU'));setError('')}catch(e){if(!ctrl.signal.aborted)setError(e instanceof Error?e.message:'Ошибка загрузки')}finally{loading=false;if(!ctrl.signal.aborted)setBusy(false)}};setRates([]);setHistory([]);setError('');void load();const interval=setInterval(()=>{if(document.visibilityState==='visible')void load()},5000);return()=>{ctrl.abort();clearInterval(interval)}},[base,quote]);
 const available=useMemo(()=>[...new Set([...majorCurrencies,...rates.map(r=>r.quote)])],[rates]);
 const activeHistory=useMemo(()=>history.filter(r=>r.base===base&&r.quote===quote),[history,base,quote]);
 const activeRates=useMemo(()=>rates.filter(r=>r.base===base),[rates,base]);
 const series=withinPeriod(activeHistory,period),delta=pct(series),last=series.at(-1);const predicted=forecast(activeHistory,quote);const filtered=(listMode==='major'&&!search?majorCurrencies:available).filter(c=>c!==base&&`${c} ${currencyName(c)}`.toLowerCase().includes(search.toLowerCase()));
 function selectPair(b:string,q:string){if(b===q){setBase(q);setQuote(base===q?'USD':base)}else{setBase(b);setQuote(q)}}
 return <><section className="panel currency-terminal"><div className="panel-header"><div><div className="kicker">ВАЛЮТНЫЙ РЫНОК</div><h2>Каждое движение — в контексте</h2></div><div className="segmented" aria-label="Источник графика"><button aria-pressed={mode==='history'} onClick={()=>setMode('history')}>История курса</button><button aria-pressed={mode==='exchange'} onClick={()=>setMode('exchange')}>Биржевой график <ArrowUpRight size={13}/></button></div></div><div className="chart-controls"><div className="pair-controls"><label><span className="sr-only">Базовая валюта</span><select aria-label="Базовая валюта" value={base} onChange={e=>selectPair(e.target.value,quote)}>{available.map(c=><option key={c} value={c}>{c}</option>)}</select></label><button className="icon-btn swap" aria-label="Поменять валюты местами" onClick={()=>{setBase(quote);setQuote(base)}}><ArrowLeftRight size={16}/></button><label><span className="sr-only">Валюта котировки</span><select aria-label="Валюта котировки" value={quote} onChange={e=>selectPair(base,e.target.value)}>{available.filter(c=>c!==base).map(c=><option key={c} value={c}>{c}</option>)}</select></label></div>{mode==='history'&&<div className="periods" aria-label="Период истории">{[[7,'1Н'],[30,'1М'],[90,'3М'],[180,'6М'],[365,'1Г']].map(([days,label])=><button key={days} aria-pressed={period===days} onClick={()=>setPeriod(Number(days))}>{label}</button>)}</div>}</div>
 <div className="currency-mode-view" key={mode}>{mode==='exchange'?<TradingChart symbol={`FX_IDC:${base}${quote}`} theme={theme}/>:<><div className="price-line"><strong>{last?displayRate(last.rate):'—'} <small>{quote}</small></strong>{delta!==null&&<span className={delta>=0?'positive':'negative'}>{delta>=0?'+':''}{delta.toFixed(2)}% <small>за период</small></span>}</div><div className="chart-subtitle">1 {base} · {last?`курс на ${last.date}`:'ожидание данных'} <span className="daily-badge"><Clock3 size={12}/> Дневные данные</span></div>{error&&<div className="inline-error" role="status">{error}. {activeHistory.length?'Показана последняя загруженная история.':''} Повторим автоматически.</div>}
 <div className="fx-chart"><div className="currency-chart-view" key={`${base}:${quote}:${period}:${series.length>1?'ready':'waiting'}`}>{series.length>1?<ResponsiveContainer width="100%" height="100%"><AreaChart data={series} margin={{top:20,right:12,bottom:4,left:0}}><defs><linearGradient id="fxGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#59c9a5" stopOpacity={.23}/><stop offset="100%" stopColor="#59c9a5" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--line)" vertical={false} strokeDasharray="3 5"/><XAxis dataKey="date" tickFormatter={d=>new Date(d).toLocaleDateString('ru-RU',{day:'numeric',month:'short'})} minTickGap={45} tick={{fill:'var(--muted-foreground)',fontSize:12}} axisLine={false} tickLine={false}/><YAxis domain={['auto','auto']} tickFormatter={displayRate} width={72} tick={{fill:'var(--muted-foreground)',fontSize:12}} axisLine={false} tickLine={false} orientation="right"/><Tooltip contentStyle={{background:'var(--surface)',border:'1px solid var(--line)',borderRadius:10,color:'var(--text)'}} labelFormatter={label=>new Date(String(label)).toLocaleDateString('ru-RU')} formatter={(v)=>[displayRate(Number(v)),`${base}/${quote}`]}/><Area type="monotone" dataKey="rate" stroke="#59c9a5" strokeWidth={2.5} fill="url(#fxGradient)" isAnimationActive={false}/></AreaChart></ResponsiveContainer>:<div className="empty"><ChartNoAxesCombined size={32}/><h3>{busy?'Загружаем историю…':'История недоступна'}</h3><p>{busy?'Получаем реальные данные источника.':'Выберите другую валютную пару или повторите запрос.'}</p></div>}</div></div><div className="chart-footer"><span><span className={busy?'dot amber':'dot'}/>{busy?'Проверяем данные…':`Проверено ${checked||'—'}`}</span><span>Frankfurter · проверка каждые 5 секунд · обновление курса раз в день</span></div></>}</div>
 </section>{expanded&&<><section className="panel currency-list"><div className="panel-header"><div><h2>Валюты мира <span className="counter">{filtered.length}</span></h2><p>Сколько единиц валюты вы получите за 1 {base}</p></div><div className="segmented"><button aria-pressed={listMode==='major'} onClick={()=>setListMode('major')}>Основные</button><button aria-pressed={listMode==='all'} onClick={()=>setListMode('all')}>Все доступные</button></div></div><label className="field-search"><Search size={18}/><input aria-label="Поиск валюты" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Код или название валюты…"/></label><div className="currency-grid">{filtered.map(c=>{const r=activeRates.find(r=>r.quote===c);return <button className={`currency-tile ${c===quote?'selected':''}`} key={c} onClick={()=>setQuote(c)} aria-pressed={c===quote}><span className="currency-monogram" style={{background:'transparent',borderRadius:0}}><CurrencyIcon code={c}/></span><span className="currency-identity"><b>{c}</b><small>{currencyName(c)}</small></span><span className="currency-value"><b>{r?displayRate(r.rate):'—'}</b><small>{r?r.date:'Нет курса'}</small></span><ArrowUpRight size={15}/></button>})}</div>{!filtered.length&&<div className="empty">По этому запросу валюты не найдены.</div>}</section><section className="panel forecast-panel"><div className="panel-header"><div><div className="kicker">СЦЕНАРИЙ · 22 ТОРГОВЫХ ДНЯ</div><h2>{quote} относительно {base}</h2></div><Globe2 size={22}/></div>{predicted?<div className="forecast-stats"><div><small>Историческая экстраполяция</small><strong className={predicted.mid>=0?'positive':'negative'}>{predicted.mid>=0?'+':''}{predicted.mid.toFixed(2)}%</strong></div><div><small>Расчётный диапазон</small><strong>{predicted.low.toFixed(2)}% … {predicted.high.toFixed(2)}%</strong></div></div>:<p className="muted">Недостаточно свежей истории: нужно 40 наблюдений, последнее не старше 7 дней.</p>}<p className="method-note">Экстраполяция последних 60 наблюдений, диапазон ±1,96 исторического стандартного отклонения. Не учитывает новостные шоки, не прошла проверку предсказательной точности и не является вероятностью прибыли.</p></section></>}</>
}


