"use client";
import {useState} from 'react';
import type {SourceHealth} from '@/lib/news';
export default function SourcesPanel({health=[],checkedAt}:{health?:SourceHealth[];checkedAt?:string}){
 const [query,setQuery]=useState(''),[mode,setMode]=useState('all');
 const available=health.filter(s=>s.status!=='error').length,publishers=new Set(health.map(s=>s.publisher)).size;
 const shown=health.filter(s=>(mode==='all'||(mode==='error'?s.status==='error':s.status!=='error'))&&`${s.name} ${s.publisher} ${s.kind}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="panel sources-directory"><div className="panel-header"><div><div className="kicker">ПРОЗРАЧНОСТЬ ДАННЫХ</div><h2>Источники информации</h2></div></div><div className="sources-summary"><div><strong>{health.length||'—'}</strong><span>подключённых лент</span></div><div><strong>{publishers||'—'}</strong><span>редакций и организаций</span></div><div><strong>{health.length?available:'—'}</strong><span>ответили при проверке</span></div></div><p className="method-note">Сбор запланирован каждые 5 минут, возможна задержка запуска GitHub. Страница проверяет опубликованный результат каждые 5 секунд. Это периодический опрос, не поток новостей в реальном времени. {checkedAt&&`Последний сбор: ${new Date(checkedAt).toLocaleString('ru-RU')}.`}</p><p className="method-note">Первичные источники сообщают собственные данные; корпоративные ленты отражают позицию компании. Несколько лент одной редакции не считаются независимыми подтверждениями. Доступность RSS не означает, что исходная статья бесплатна.</p><div className="filter-bar"><label className="field-search"><input aria-label="Поиск источника" placeholder="Редакция, организация или лента…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Статус источника" value={mode} onChange={e=>setMode(e.target.value)}><option value="all">Все статусы</option><option value="ok">Ответили</option><option value="error">Недоступны</option></select></div><div className="source-directory-list">{shown.map(s=><article key={s.id} className="source-entry"><div><b>{s.publisher}</b><span className={s.status==='error'?'negative':'positive'}>{s.status==='error'?'Не ответил':s.status==='unchanged'?'Без изменений':'Получено'}</span></div><p>{s.name}</p><small>{s.kind} · {s.articles} материалов в ленте</small><small>Проверка: {new Date(s.checkedAt).toLocaleString('ru-RU')}</small><small>Успешное получение: {s.lastSuccessAt?new Date(s.lastSuccessAt).toLocaleString('ru-RU'):'пока не было'}</small>{s.latestArticleAt&&Date.now()-Date.parse(s.latestArticleAt)>30*86400000&&<p className="muted">Новых публикаций за последние 30 дней нет.</p>}<small>Последняя публикация: {s.latestArticleAt?new Date(s.latestArticleAt).toLocaleString('ru-RU'):'дата не указана'}</small>{s.status==='error'&&<p className="negative">{s.error}. Повторим при следующем сборе.</p>}<a href={s.url} target="_blank" rel="noopener noreferrer">Открыть RSS / Atom ↗</a></article>)}</div>{!shown.length&&<div className="empty">{health.length?'Источников по этому фильтру нет.':'Статусы появятся после загрузки снимка.'}</div>}</section>
}

