import {contextExcerpt} from './news-summary.ts';
import {sources,type NewsSource} from './news-sources.ts';
export {sources};
export type Story={title:string;source:string;sourceId?:string;publisher?:string;sourceKind?:string;url:string;date:string;category:string;summary:string;signal:number;assets:string[];catalyst?:string;concern?:string;summaryKind?:string;firstSeenAt?:string;ru?:{title:string;summary:string;hash:string;model:string;translatedAt:string};translationStatus?:'ready'|'pending'|'failed'|'unconfigured'};
function clean(s:string){return s.replace(/&#(x[0-9a-f]+|[0-9]+);/gi,(entity,value)=>{const n=value[0].toLowerCase()==='x'?parseInt(value.slice(1),16):Number(value);return n>0&&n<=0x10ffff?String.fromCodePoint(n):entity}).replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&apos;/g,"'").replace(/&quot;/g,'"').replace(/&#(?:39|8217);/g,"'").replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}
function tag(s:string,t:string){return clean(s.match(new RegExp(`<${t}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${t}>`,'i'))?.[1]||'')}
const names:Record<string,string[]>= {NVDA:['nvidia'],MSFT:['microsoft'],AAPL:['apple','iphone','ipad','macbook'],AMZN:['amazon','aws'],TSLA:['tesla'],GOOGL:['alphabet','google'],META:['meta platforms','facebook','instagram'],AVGO:['broadcom'],AMD:['advanced micro devices','amd'],INTC:['intel'],ORCL:['oracle'],CRM:['salesforce'],ADBE:['adobe'],NFLX:['netflix'],PLTR:['palantir'],JPM:['jpmorgan','jp morgan'],BAC:['bank of america'],GS:['goldman sachs'],V:['visa'],MA:['mastercard'],WMT:['walmart'],COST:['costco'],KO:['coca-cola'],PEP:['pepsico'],PG:['procter & gamble'],MCD:["mcdonald"],DIS:['disney'],JNJ:['johnson & johnson'],LLY:['eli lilly'],PFE:['pfizer'],XOM:['exxon'],CVX:['chevron'],BA:['boeing'],ASML:['asml'],SAP:['sap se'],SIE:['siemens'],MC:['lvmh'],AIR:['airbus'],NESN:['nestle','nestlé'],NOVO_B:['novo nordisk'],'7203':['toyota'],'6758':['sony'],'005930':['samsung'],'2330':['tsmc','taiwan semiconductor'],'700':['tencent'],'9988':['alibaba'],'1810':['xiaomi'],'1211':['byd'],RELIANCE:['reliance industries'],SHOP:['shopify'],MELI:['mercadolibre']};
const positives:[RegExp,string][]=[[/\b(?:earnings|profit|revenue|sales)\b.{0,60}\b(?:beat|grow|growth|rise|jump|surge|record|higher|increase)/i,'В сообщении есть признаки улучшения финансовых результатов.'],[/\b(?:raise[sd]?|boost[sd]?|increase[sd]?)\b.{0,35}\b(?:forecast|guidance|dividend|outlook)/i,'Компания повышает прогноз или выплаты — возможный позитивный фактор.'],[/\b(?:launch(?:es|ed)?|unveil(?:s|ed)?|introduc(?:es|ed)|rolls? out)\b/i,'Новый продукт может расширить спрос; его вклад в прибыль ещё нужно подтвердить.'],[/\b(?:wins?|secures?|signs?)\b.{0,50}\b(?:deal|contract|partnership|approval)/i,'Новый контракт, партнёрство или разрешение может поддержать бизнес.'],[/\b(?:growth|grows|expands|record demand)\b/i,'Источник сообщает о росте; проверьте устойчивость этого фактора.']];
const negative=/\b(?:loss(?:es)?|lawsuit|recall|fraud|miss(?:es|ed)? estimates|cuts? (?:forecast|guidance)|decline|falls?|drops?|probe|antitrust|layoffs?|breach|plunge|warns?)\b/i;
export function analyze(title:string,category:string){const assets=Object.entries(names).filter(([,aliases])=>aliases.some(a=>new RegExp(`\\b${a.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'i').test(title))).map(([ticker])=>ticker);const catalyst=positives.find(([rule])=>rule.test(title))?.[1];const concern=negative.test(title)?'В новости есть негативный фактор. Он может перевесить аргументы за покупку.':undefined;const signal=concern?-1:catalyst?1:0;if(/\bdividends?\b/i.test(title))category='Дивиденды';if(/\b(currency|currencies|exchange rate|dollar|euro)\b/i.test(title))category='Валюты';return{signal,assets,category,catalyst,concern}}
export function parseFeed(xml:string,source:Pick<NewsSource,'name'|'category'> & Partial<NewsSource>):Story[]{
 const blocks=[...xml.matchAll(/<(item|entry)\b[^>]*>([\s\S]*?)<\/\1>/gi)];
 return blocks.slice(0,25).map(m=>{const body=m[2],title=tag(body,'title');const atomLinks=[...body.matchAll(/<link\b([^>]+)\/?\s*>/gi)].map(x=>({href:x[1].match(/href=["']([^"']+)["']/i)?.[1],rel:x[1].match(/rel=["']([^"']+)["']/i)?.[1]}));
 const rawUrl=tag(body,'link')||clean(atomLinks.find(x=>!x.rel||x.rel==='alternate')?.href||'');let url='';try{url=rawUrl?new URL(rawUrl,source.url).href:''}catch{};
 const date=tag(body,'pubDate')||tag(body,'published')||tag(body,'dc:date')||tag(body,'updated');
 const description=tag(body,'description')||tag(body,'summary');const analysis=analyze(title,source.category);
 return{title,source:source.publisher||source.name,sourceId:source.id,publisher:source.publisher||source.name,sourceKind:source.kind,url,date:Number.isFinite(Date.parse(date))?new Date(date).toISOString():'',summary:description?contextExcerpt(description):title,summaryKind:description?'Кратко из RSS источника':'Источник передал только заголовок',...analysis};
 }).filter(n=>n.title&&/^https?:\/\//i.test(n.url));
}
export type SourceHealth={id:string;name:string;publisher:string;url:string;homepage:string;kind:string;status:'ok'|'unchanged'|'error';checkedAt:string;lastSuccessAt?:string;latestArticleAt?:string;articles:number;error?:string};
export type FeedCache={etag?:string;modified?:string;lastSuccessAt?:string;news:Story[]};
export type CollectorCache=Record<string,FeedCache>;
export function deduplicate(news:Story[]){const urls=new Set<string>(),titles=new Set<string>();return news.filter(n=>{let url:string;try{const u=new URL(n.url);u.hash='';for(const key of [...u.searchParams.keys()])if(/^(utm_|fbclid|gclid)/.test(key))u.searchParams.delete(key);url=u.href}catch{return false}const title=n.title.toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');if(urls.has(url)||titles.has(title))return false;urls.add(url);titles.add(title);return true})}
export async function collectNews(previous:CollectorCache={},sourceList:NewsSource[]=sources,fetcher:typeof fetch=fetch){
 const cache:CollectorCache={},health:SourceHealth[]=[];let cursor=0;
 // Round robin across hosts to avoid a burst of requests against one publisher.
 const groups=new Map<string,NewsSource[]>();for(const s of sourceList){const host=new URL(s.url).host;groups.set(host,[...(groups.get(host)||[]),s])}const queue:NewsSource[]=[];while([...groups.values()].some(g=>g.length))for(const g of groups.values()){const s=g.shift();if(s)queue.push(s)}
 await Promise.all(Array.from({length:Math.min(8,queue.length)},async()=>{while(cursor<queue.length){const source=queue[cursor++],old=previous[source.id];const checkedAt=new Date().toISOString();const base={id:source.id,name:source.name,publisher:source.publisher,url:source.url,homepage:source.homepage,kind:source.kind,checkedAt};
 try{const headers:Record<string,string>={'User-Agent':'MeridianMarketReader/4.0 (+https://esforgary.github.io/market-analysis/)','Accept':'application/rss+xml, application/atom+xml, application/xml, text/xml'};if(old?.etag)headers['If-None-Match']=old.etag;if(old?.modified)headers['If-Modified-Since']=old.modified;
 const response=await fetcher(source.url,{headers,signal:AbortSignal.timeout(12000)});let entries:Story[];
 if(response.status===304&&old){entries=old.news.map(n=>({...n,firstSeenAt:n.firstSeenAt||checkedAt}));cache[source.id]={...old,news:entries,lastSuccessAt:checkedAt}}else{if(!response.ok)throw Error('HTTP '+response.status);const xml=await response.text();if(xml.length>4000000)throw Error('Слишком большой ответ');if(!/<(?:rss|feed|rdf:RDF)\b/i.test(xml))throw Error('Источник вернул не RSS/Atom');entries=parseFeed(xml,source).map(n=>({...n,firstSeenAt:old?.news.find(p=>p.url===n.url)?.firstSeenAt||checkedAt}));if(!entries.length)throw Error('В ленте нет распознаваемых публикаций');cache[source.id]={etag:response.headers.get('etag')||undefined,modified:response.headers.get('last-modified')||undefined,lastSuccessAt:checkedAt,news:entries}}
 const dates=entries.map(n=>n.date).filter(Boolean).sort();health.push({...base,status:response.status===304?'unchanged':'ok',lastSuccessAt:checkedAt,latestArticleAt:dates.at(-1),articles:entries.length});
 }catch(e){if(old)cache[source.id]=old;health.push({...base,status:'error',lastSuccessAt:old?.lastSuccessAt,latestArticleAt:old?.news.map(n=>n.date).filter(Boolean).sort().at(-1),articles:old?.news.length||0,error:e instanceof Error?e.message:'Ошибка источника'})}
 }}));
 const news=deduplicate(Object.values(cache).flatMap(c=>c.news)).filter(n=>!n.date||(Date.parse(n.date)>=Date.now()-30*86400000&&Date.parse(n.date)<=Date.now()+5*60000)).sort((a,b)=>(Date.parse(b.date)||0)-(Date.parse(a.date)||0));health.sort((a,b)=>a.publisher.localeCompare(b.publisher)||a.name.localeCompare(b.name));const failed=health.filter(h=>h.status==='error').length;
 return{cache,snapshot:{news,errors:failed?[failed+' из '+health.length+' лент не ответили. Статусы — в разделе «Источники».']:[],fetchedAt:new Date().toISOString(),sourceHealth:health,sourceCount:sourceList.length,publisherCount:new Set(sourceList.map(s=>s.publisher)).size,availableCount:health.length-failed,collectionIntervalSeconds:300}};
}
export async function fetchNews(){return(await collectNews()).snapshot}

