export type Story={title:string;source:string;url:string;date:string;category:string;summary:string;signal:number;assets:string[];catalyst?:string;concern?:string;summaryKind?:string};
export const sources=[{name:'Federal Reserve',url:'https://www.federalreserve.gov/feeds/press_monetary.xml',category:'Экономика'},{name:'European Central Bank',url:'https://www.ecb.europa.eu/rss/press.html',category:'Экономика'},{name:'TechCrunch',url:'https://techcrunch.com/feed/',category:'Технологии'},{name:'CNBC Markets',url:'https://www.cnbc.com/id/100003114/device/rss/rss.html',category:'Экономика'},{name:'CNBC Technology',url:'https://www.cnbc.com/id/19854910/device/rss/rss.html',category:'Технологии'}];
function clean(s:string){return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&apos;/g,"'").replace(/&quot;/g,'"').replace(/&#(?:39|8217);/g,"'").replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}
function tag(s:string,t:string){return clean(s.match(new RegExp(`<${t}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${t}>`,'i'))?.[1]||'')}
const names:Record<string,string[]>= {NVDA:['nvidia'],MSFT:['microsoft'],AAPL:['apple','iphone','ipad','macbook'],AMZN:['amazon','aws'],TSLA:['tesla'],GOOGL:['alphabet','google'],META:['meta platforms','facebook','instagram'],AVGO:['broadcom'],AMD:['advanced micro devices','amd'],INTC:['intel'],ORCL:['oracle'],CRM:['salesforce'],ADBE:['adobe'],NFLX:['netflix'],PLTR:['palantir'],JPM:['jpmorgan','jp morgan'],BAC:['bank of america'],GS:['goldman sachs'],V:['visa'],MA:['mastercard'],WMT:['walmart'],COST:['costco'],KO:['coca-cola'],PEP:['pepsico'],PG:['procter & gamble'],MCD:["mcdonald"],DIS:['disney'],JNJ:['johnson & johnson'],LLY:['eli lilly'],PFE:['pfizer'],XOM:['exxon'],CVX:['chevron'],BA:['boeing'],ASML:['asml'],SAP:['sap se'],SIE:['siemens'],MC:['lvmh'],AIR:['airbus'],NESN:['nestle','nestlé'],NOVO_B:['novo nordisk'],'7203':['toyota'],'6758':['sony'],'005930':['samsung'],'2330':['tsmc','taiwan semiconductor'],'700':['tencent'],'9988':['alibaba'],'1810':['xiaomi'],'1211':['byd'],RELIANCE:['reliance industries'],SHOP:['shopify'],MELI:['mercadolibre']};
const positives:[RegExp,string][]=[[/\b(?:earnings|profit|revenue|sales)\b.{0,60}\b(?:beat|grow|growth|rise|jump|surge|record|higher|increase)/i,'В сообщении есть признаки улучшения финансовых результатов.'],[/\b(?:raise[sd]?|boost[sd]?|increase[sd]?)\b.{0,35}\b(?:forecast|guidance|dividend|outlook)/i,'Компания повышает прогноз или выплаты — возможный позитивный фактор.'],[/\b(?:launch(?:es|ed)?|unveil(?:s|ed)?|introduc(?:es|ed)|rolls? out)\b/i,'Новый продукт может расширить спрос; его вклад в прибыль ещё нужно подтвердить.'],[/\b(?:wins?|secures?|signs?)\b.{0,50}\b(?:deal|contract|partnership|approval)/i,'Новый контракт, партнёрство или разрешение может поддержать бизнес.'],[/\b(?:growth|grows|expands|record demand)\b/i,'Источник сообщает о росте; проверьте устойчивость этого фактора.']];
const negative=/\b(?:loss(?:es)?|lawsuit|recall|fraud|miss(?:es|ed)? estimates|cuts? (?:forecast|guidance)|decline|falls?|drops?|probe|antitrust|layoffs?|breach|plunge|warns?)\b/i;
export function analyze(title:string,category:string){const assets=Object.entries(names).filter(([,aliases])=>aliases.some(a=>new RegExp(`\\b${a.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'i').test(title))).map(([ticker])=>ticker);const catalyst=positives.find(([rule])=>rule.test(title))?.[1];const concern=negative.test(title)?'В новости есть негативный фактор. Он может перевесить аргументы за покупку.':undefined;const signal=concern?-1:catalyst?1:0;if(/\bdividends?\b/i.test(title))category='Дивиденды';if(/\b(currency|currencies|exchange rate|dollar|euro)\b/i.test(title))category='Валюты';return{signal,assets,category,catalyst,concern}}
export function parseFeed(xml:string,source:(typeof sources)[number]):Story[]{return [...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].slice(0,25).map(m=>{const title=tag(m[1],'title'),url=tag(m[1],'link'),date=tag(m[1],'pubDate'),description=tag(m[1],'description');const analysis=analyze(title,source.category);const summary=description?description.split(/(?<=[.!?])\s+/).slice(0,2).join(' ').slice(0,340):title;return{title,source:source.name,url,date:Number.isFinite(Date.parse(date))?new Date(date).toISOString():'',summary,summaryKind:description?'Кратко из RSS источника':'Источник передал только заголовок',...analysis}}).filter(n=>n.title&&/^https?:\/\//i.test(n.url))}
export async function fetchNews(){const results=await Promise.allSettled(sources.map(async source=>{const r=await fetch(source.url,{headers:{'User-Agent':'MeridianMarketReader/3.0'},signal:AbortSignal.timeout(14000)});if(!r.ok)throw Error('Unavailable');const news=parseFeed(await r.text(),source);if(!news.length)throw Error('Empty feed');return news}));const errors:string[]=[];const news=results.flatMap((r,i)=>{if(r.status==='fulfilled')return r.value;errors.push(`${sources[i].name}: источник недоступен`);return[]}).filter((n,i,a)=>a.findIndex(x=>x.url===n.url)===i).sort((a,b)=>(Date.parse(b.date)||0)-(Date.parse(a.date)||0));return {news,errors,fetchedAt:new Date().toISOString()}}

