export const dynamic = 'force-dynamic';
type Rate={date:string;base:string;quote:string;rate:number};
const sources=[{name:'Federal Reserve',url:'https://www.federalreserve.gov/feeds/press_monetary.xml',category:'Экономика'},{name:'European Central Bank',url:'https://www.ecb.europa.eu/rss/press.html',category:'Экономика'},{name:'TechCrunch',url:'https://techcrunch.com/feed/',category:'Технологии'}];
function clean(s:string){return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#(?:39|8217);/g,"'").trim()}
function tag(s:string,t:string){return clean(s.match(new RegExp(`<${t}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${t}>`,'i'))?.[1]||'')}
export function analyze(title:string,category:string){const t=title.toLowerCase();let signal=0;for(const word of ['growth','grows','rise','rises','increase','increases','profit','expands'])if(new RegExp(`\\b${word}\\b`).test(t))signal++;for(const word of ['decline','declines','fall','falls','loss','losses','cuts','recession'])if(new RegExp(`\\b${word}\\b`).test(t))signal--;const assets:string[]=[];if(/\bnvidia\b/.test(t))assets.push('NVDA');if(/\bmicrosoft\b/.test(t))assets.push('MSFT');if(/\b(dividend|dividends)\b/.test(t))category='Дивиденды';if(/\b(currency|currencies|exchange rate|dollar|euro)\b/.test(t))category='Валюты';return{signal:Math.sign(signal),assets,category}}
let cached:{until:number;data:unknown}|null=null;
async function get(url:string){const r=await fetch(url,{headers:{'User-Agent':'MeridianMarketReader/1.0','Accept':'application/json, application/rss+xml, application/xml, text/xml'},signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error(`HTTP ${r.status}`);return r}
function rates(v:unknown):Rate[]{if(!Array.isArray(v))throw Error('Invalid rate response');return v.filter((x):x is Rate=>!!x&&typeof x.date==='string'&&['USD','GBP','CHF','JPY'].includes(x.quote)&&typeof x.rate==='number'&&Number.isFinite(x.rate)&&x.rate>0)}
export async function GET(){if(cached&&Date.now()<cached.until)return Response.json(cached.data);const start=new Date();start.setUTCFullYear(start.getUTCFullYear()-1);const urls=['https://api.frankfurter.dev/v2/rates?base=EUR&quotes=USD,GBP,CHF,JPY',`https://api.frankfurter.dev/v2/rates?base=EUR&quotes=USD,GBP,CHF,JPY&from=${start.toISOString().slice(0,10)}`];const results=await Promise.allSettled([...sources.map(async s=>{const xml=await(await get(s.url)).text();const items=[...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].slice(0,10);if(!items.length)throw Error('Empty feed');return items.map(m=>{const title=tag(m[1],'title'),url=tag(m[1],'link'),date=tag(m[1],'pubDate');const analysis=analyze(title,s.category);return{title,source:s.name,url,date:Number.isFinite(Date.parse(date))?new Date(date).toISOString():'',summary:'Лексическая оценка заголовка. Откройте первоисточник для контекста; тональность не определяет направление цены актива.',...analysis}}).filter(n=>n.title&&/^https?:\/\//.test(n.url))}),...urls.map(async u=>rates(await(await get(u)).json()))]);const errors:string[]=[];const news=results.slice(0,3).flatMap((r,i)=>{if(r.status==='fulfilled')return r.value as {title:string;date:string;url:string}[];errors.push(`${sources[i].name}: источник недоступен`);return[]}).filter((n,i,a)=>a.findIndex(x=>x.url===n.url)===i).sort((a,b)=>(Date.parse(b.date)||0)-(Date.parse(a.date)||0));const current=results[3],history=results[4];if(current.status==='rejected')errors.push('Курсы валют недоступны');if(history.status==='rejected')errors.push('История валют недоступна');const data={news,rates:current.status==='fulfilled'?current.value:[],history:history.status==='fulfilled'?history.value:[],errors,fetchedAt:new Date().toISOString()};cached={until:Date.now()+(errors.length?30000:300000),data};return Response.json(data,{headers:{'Cache-Control':'no-store'}})}
